updated version and exit on failure to github action

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -79,6 +79,8 @@ jobs:
 
             - name: Create dist and docker-dist
               run: |
+                  set -ex  # -e: exit on error, -x: debug
+
                   # Build JavaScript
                   npm run build
                   echo "Built to dist/"
@@ -86,8 +88,6 @@ jobs:
                   # Create the docker-dist directory
                   mkdir docker-dist
                   echo "Created docker-dist"
-
-                  ls docker-dist
 
                   # Copy necessary files to the docker-dist directory
                   cp Dockerfile docker-dist
@@ -98,10 +98,6 @@ jobs:
 
                   # Change package.json type to commonjs in docker-dist directory
                   jq '.type="commonjs"' docker-dist/package.json > docker-dist/package.json.tmp && mv docker-dist/package.json.tmp docker-dist/package.json
-
-                  # Update config.js for Docker compatibility
-                  # sed -i.bak 's/host: "127.0.0.1"/host: "host.docker.internal"/' docker-dist/config.js
-                  # rm docker-dist/config.js.bak
 
                   # Replace DB credentials in config.js
                   sed -i "s/root/${{ secrets.DB_USERNAME }}/g" docker-dist/config.js
